spring:
  datasource:
    url: jdbc:h2:mem:testdb;NON_KEYWORDS=USER
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
server:
  port: 7070